---
title: "Correlation of computed centrality measures"
output: html_document
date: '2023-11-13'
---

```{r setup, include=FALSE}
.libPaths(c("/home/pravich2/rlibs/4.0.2/gcc/9.3.0", "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-markdown-1.1-g65guwxov2k2maedod2wedfr5jon6egu/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-knitr-1.28-cn7dhiz6mwl53op4gpecto35sljr4muz/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-yaml-2.2.0-ttbd4ipwa5jccbl733saf7c2zijmdixr/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-stringr-1.4.0-qbr2amu2xnxkicncfgvu7klzll4dg46v/rlib/R/library",
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-stringi-1.4.3-n22ruwgbot2i3becz3comesic75s47r6/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-magrittr-1.5-wy6q2ditqph62m4dib33mds3wsbluj7g/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-glue-1.4.1-5ejojwbzonzsvkmwa7o2h57gpbsutbl4/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-mime-0.7-n4hlpgd2g5fdbt3idl374eftb2utep3r/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-highr-0.8-rcw4hovy72yo4wj6mfrgtgbkovlqb3fg/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-evaluate-0.14-laasv6wsxntd3ht34ydl4ott7zzfthko/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-4.0.2-amdvcpog4ugspqwwx3ari7pzkmckelu6/rlib/R/library"))
knitr::opts_chunk$set(echo = TRUE)
```

## Properties of data aggregated to form context-specific networks

This script reproduces Fig 5, and Supplementary figure 13. 

```{r}
library(ggplot2)
library(cowplot)
library(RColorBrewer)
library(rstatix)
library(igraph)
library(stringr)
library(ggpubr)
library(pheatmap)

get_legend<-function(myggplot){
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}

read_centrality <- function(net, nStudies, lambda){
  centrality_list <- lapply(lambda, function(ilambda){
    df <- readRDS(paste0("/data/abattle4/prashanthi/recount3_paper/results/weighted_cov_networks/", net, "/net_", nStudies, "/centrality_", ilambda, ".rds"))
    df <- df[ ,!colnames(df) == "eigen_centrality"]
  })
  centrality_list
}

normal_consensus_centrality <- read_centrality("normal_consensus", "629", c("0.14", "0.16", "0.18", "0.20"))
all_consensus_centrality <- read_centrality("all_consensus", "966", c("0.14", "0.16", "0.18", "0.20"))

normal_consensus_corr <- lapply(normal_consensus_centrality, function(df){
  res <- cor(df[ ,c(2:7)])
  colnames(res) <- str_to_title(colnames(res))
  rownames(res) <- str_to_title(rownames(res))
  colnames(res)[colnames(res) == "Page_rank"] <- "PageRank"
  rownames(res)[rownames(res) == "Page_rank"] <- "PageRank"
  res
})

all_consensus_corr <- lapply(all_consensus_centrality, function(df){
  res <- cor(df[ ,c(2:7)])
  colnames(res) <- str_to_title(colnames(res))
  rownames(res) <- str_to_title(rownames(res))
  colnames(res)[colnames(res) == "Page_rank"] <- "PageRank"
  rownames(res)[rownames(res) == "Page_rank"] <- "PageRank"
  res
})

```


```{r}
p_all <- lapply(all_consensus_corr, function(res){
  ggcorrplot(res, hc.order = TRUE, outline.color = "white") + scale_fill_gradient2(limit = c(0,1), low = "white", high =  "blue") +  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"), legend.title=element_blank(), legend.position = "bottom", legend.key.width = unit(2.5, "cm"), plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
          legend.text = element_text(size = 12, face = "bold"),
          axis.title = element_text(size = 12, face = "bold"))
})

all_legend <- get_legend(p_all[[1]])
p_all <- lapply(p_all, function(p){
  p + theme(legend.position = "none")
})
p_all[[1]] <- p_all[[1]] + ggtitle("Lambda = 0.14") 
p_all[[2]] <- p_all[[2]] + ggtitle("Lambda = 0.16") 
p_all[[3]] <- p_all[[3]] + ggtitle("Lambda = 0.18") 
p_all[[4]] <- p_all[[4]] + ggtitle("Lambda = 0.20") 

title_all <- ggdraw() + 
    draw_label(
      "Universal consensus",
      fontface = 'bold',
      x = 0,
      size = 16,
      hjust = 0
    ) +
    theme(
      # add margin on the left of the drawing canvas,
      # so title is aligned with left edge of first plot
      plot.margin = margin(0, 0, 0, 7)
    )
plot_grid(title_all, plot_grid(p_all[[1]], p_all[[2]],p_all[[3]], p_all[[4]], nrow = 1), all_legend,  nrow = 3, rel_heights =  c(0.1, 1, 0.3))

```


```{r}
p_normal <- lapply(normal_consensus_corr, function(res){
  ggcorrplot(res, hc.order = TRUE, outline.color = "white") + scale_fill_gradient2(limit = c(0,1), low = "white", high =  "blue") +  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"), legend.title=element_blank(), legend.position = "bottom", legend.key.width = unit(2.5, "cm"), plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
          legend.text = element_text(size = 12, face = "bold"),
          axis.title = element_text(size = 12, face = "bold"))
})

normal_legend <- get_legend(p_normal[[1]])
p_normal <- lapply(p_normal, function(p){
  p + theme(legend.position = "none")
})
p_normal[[1]] <- p_normal[[1]] + ggtitle("Lambda = 0.14") 
p_normal[[2]] <- p_normal[[2]] + ggtitle("Lambda = 0.16") 
p_normal[[3]] <- p_normal[[3]] + ggtitle("Lambda = 0.18") 
p_normal[[4]] <- p_normal[[4]] + ggtitle("Lambda = 0.20") 

title_normal <- ggdraw() + 
    draw_label(
      "Non-cancer consensus",
      fontface = 'bold',
      x = 0,
      size = 16,
      hjust = 0
    ) +
    theme(
      # add margin on the left of the drawing canvas,
      # so title is aligned with left edge of first plot
      plot.margin = margin(0, 0, 0, 7)
    )
plot_grid(title_normal, plot_grid(p_normal[[1]], p_normal[[2]],p_normal[[3]], p_normal[[4]], nrow = 1), normal_legend,  nrow = 3, rel_heights =  c(0.1, 1, 0.3))

```


```{r, fig.height=8, fig.width=8}
blood_consensus_centrality <- read_centrality("blood/all", "65", c("0.18", "0.20", "0.22", "0.24"))
cns_consensus_centrality <- read_centrality("central_nervous_system/all", "53", c("0.24", "0.26", "0.28", "0.30"))

blood_consensus_corr <- lapply(blood_consensus_centrality, function(df){
  res <- cor(df[ ,c(2:7)])
  colnames(res) <- str_to_title(colnames(res))
  rownames(res) <- str_to_title(rownames(res))
  colnames(res)[colnames(res) == "Page_rank"] <- "PageRank"
  rownames(res)[rownames(res) == "Page_rank"] <- "PageRank"
  res
})

cns_consensus_corr <- lapply(cns_consensus_centrality, function(df){
  res <- cor(df[ ,c(2:7)])
  colnames(res) <- str_to_title(colnames(res))
  rownames(res) <- str_to_title(rownames(res))
  colnames(res)[colnames(res) == "Page_rank"] <- "PageRank"
  rownames(res)[rownames(res) == "Page_rank"] <- "PageRank"
  res
})


```

```{r, fig.height=8, fig.width=8}
p_blood <- lapply(blood_consensus_corr, function(res){
  ggcorrplot(res, hc.order = TRUE, outline.color = "white") + scale_fill_gradient2(limit = c(0,1), low = "white", high =  "blue") +  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"), legend.title=element_blank(), legend.position = "bottom", legend.key.width = unit(2.5, "cm"), plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
          legend.text = element_text(size = 12, face = "bold"),
          axis.title = element_text(size = 12, face = "bold"))
})

blood_legend <- get_legend(p_blood[[1]])
p_blood <- lapply(p_blood, function(p){
  p + theme(legend.position = "none")
})
p_blood[[1]] <- p_blood[[1]] + ggtitle("Lambda = 0.18") 
p_blood[[2]] <- p_blood[[2]] + ggtitle("Lambda = 0.20") 
p_blood[[3]] <- p_blood[[3]] + ggtitle("Lambda = 0.22") 
p_blood[[4]] <- p_blood[[4]] + ggtitle("Lambda = 0.24") 

title_blood <- ggdraw() + 
    draw_label(
      "Blood",
      fontface = 'bold',
      x = 0,
      size = 16,
      hjust = 0
    ) +
    theme(
      # add margin on the left of the drawing canvas,
      # so title is aligned with left edge of first plot
      plot.margin = margin(0, 0, 0, 7)
    )
plot_grid(title_blood, plot_grid(p_blood[[1]], p_blood[[2]],p_blood[[3]], p_blood[[4]], nrow = 1), blood_legend,  nrow = 3, rel_heights =  c(0.1, 1, 0.3))

```

```{r, fig.height=8, fig.width=8}
p_cns <- lapply(cns_consensus_corr, function(res){
  ggcorrplot(res, hc.order = TRUE, outline.color = "white") + scale_fill_gradient2(limit = c(0,1), low = "white", high =  "blue") +  theme(plot.margin = unit(c(0, 0, 0, 0), "cm"), legend.title=element_blank(), legend.position = "bottom", legend.key.width = unit(2.5, "cm"), plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
          legend.text = element_text(size = 12, face = "bold"),
          axis.title = element_text(size = 12, face = "bold"))
})

cns_legend <- get_legend(p_cns[[1]])
p_cns <- lapply(p_cns, function(p){
  p + theme(legend.position = "none")
})
p_cns[[1]] <- p_cns[[1]] + ggtitle("Lambda = 0.24") 
p_cns[[2]] <- p_cns[[2]] + ggtitle("Lambda = 0.26") 
p_cns[[3]] <- p_cns[[3]] + ggtitle("Lambda = 0.28") 
p_cns[[4]] <- p_cns[[4]] + ggtitle("Lambda = 0.30") 

title_cns <- ggdraw() + 
    draw_label(
      "Central nervous system",
      fontface = 'bold',
      x = 0,
      size = 16,
      hjust = 0
    ) +
    theme(
      # add margin on the left of the drawing canvas,
      # so title is aligned with left edge of first plot
      plot.margin = margin(0, 0, 0, 7)
    )
plot_grid(title_cns, plot_grid(p_cns[[1]], p_cns[[2]],p_cns[[3]], p_cns[[4]], nrow = 1), cns_legend,  nrow = 3, rel_heights =  c(0.1, 1, 0.3))
```

```{r}
sessionInfo()
```

