---
title: "Heritability enrichment of context-specific networks"
output: html_document
date: '2023-11-13'
---

```{r setup, include=FALSE}
.libPaths(c("/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-markdown-1.1-g65guwxov2k2maedod2wedfr5jon6egu/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-knitr-1.28-cn7dhiz6mwl53op4gpecto35sljr4muz/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-yaml-2.2.0-ttbd4ipwa5jccbl733saf7c2zijmdixr/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-stringr-1.4.0-qbr2amu2xnxkicncfgvu7klzll4dg46v/rlib/R/library",
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-stringi-1.4.3-n22ruwgbot2i3becz3comesic75s47r6/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-magrittr-1.5-wy6q2ditqph62m4dib33mds3wsbluj7g/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-glue-1.4.1-5ejojwbzonzsvkmwa7o2h57gpbsutbl4/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-mime-0.7-n4hlpgd2g5fdbt3idl374eftb2utep3r/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-highr-0.8-rcw4hovy72yo4wj6mfrgtgbkovlqb3fg/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-evaluate-0.14-laasv6wsxntd3ht34ydl4ott7zzfthko/rlib/R/library", 
            "/data/apps/linux-centos8-cascadelake/gcc-9.3.0/r-4.0.2-amdvcpog4ugspqwwx3ari7pzkmckelu6/rlib/R/library", 
            "/home/pravich2/rlibs/4.0.2/gcc/9.3.0"))

library(ggpubr)
library(rmeta)
library(ggplot2)
library(cowplot)
library(dplyr)
library(rstatix)
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
get_legend<-function(myggplot){
  tmp <- ggplot_gtable(ggplot_build(myggplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}
```

## Blood traits

```{r, fig.width=10, fig.height=4}
homeDir <- "/data/abattle4/prashanthi/recount3_paper/"
resDir <- "/data/abattle4/prashanthi/recount3_paper/results/s_LDSC/"
blood_res <- readRDS(paste0(resDir, "blood_res.rds"))
blood_res_1 <- blood_res[blood_res$Control == "All genes", ]
blood_res_2 <- blood_res[blood_res$Control == "All genes + Baseline", ]


p1 <- ggplot() +
  geom_bar(data = blood_res_1[blood_res_1$net == "Blood consensus", ], mapping = aes(x = Centrality, y = Enrichment, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  geom_bar(data = blood_res_2[blood_res_2$net == "Blood consensus", ], mapping = aes(x = Centrality, y = Enrichment, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  scale_fill_brewer(palette = "BrBG") + theme_classic2() + xlab("") + ylab("Enrichment") +
  geom_hline(yintercept=1, colour = "black", linetype = 2, linewidth = 0.4) +
  geom_errorbar(data = blood_res_1[blood_res_1$net == "Blood consensus", ], mapping = aes(x = Centrality, ymin = Enrichment - Enrichment_std_error, ymax = Enrichment + Enrichment_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) +
  geom_errorbar(data = blood_res_2[blood_res_2$net == "Blood consensus", ], mapping = aes(x = Centrality, ymin = Enrichment - Enrichment_std_error, ymax = Enrichment + Enrichment_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) + 
  scale_alpha_manual(values = c("All genes" = 0.3, "All genes + Baseline" = 1)) + 
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom") 


p2 <- ggplot() +
  geom_bar(data = blood_res_1[blood_res_1$net == "Blood consensus", ], mapping = aes(x = Centrality, y = Coefficient, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  geom_bar(data = blood_res_2[blood_res_2$net == "Blood consensus", ], mapping = aes(x = Centrality, y = Coefficient, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  scale_fill_brewer(palette = "BrBG") + theme_classic2() + xlab("") + ylab("Coefficient") +
  geom_hline(yintercept=0, colour = "black", linetype = 2, linewidth = 0.4) +
  geom_errorbar(data = blood_res_1[blood_res_1$net == "Blood consensus", ], mapping = aes(x = Centrality, ymin = Coefficient - Coefficient_std_error, ymax = Coefficient + Coefficient_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) +
  geom_errorbar(data = blood_res_2[blood_res_2$net == "Blood consensus", ], mapping = aes(x = Centrality, ymin = Coefficient - Coefficient_std_error, ymax = Coefficient + Coefficient_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) + 
  scale_alpha_manual(values = c("All genes" = 0.4, "All genes + Baseline" = 1)) + 
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom")


title_blood_consensus <- ggdraw() + 
  draw_label(
    "Meta-Analysis of 9 Blood Traits (Blood consensus)",
    fontface = 'bold',
    x = 0,
    size = 16,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

legend_blood_consensus <- get_legend(p1)
p1 <- p1 + theme(legend.position = "none")
p2 <- p2 + theme(legend.position = "none")
plot_grid(title_blood_consensus, plot_grid(p1, p2, nrow = 1, rel_widths = c(1, 1)), legend_blood_consensus, nrow = 3, rel_heights =  c(0.1, 1, 0.1))

```

```{r, fig.height=4, fig.width=10}
p3 <- ggplot() +
  geom_bar(data = blood_res_1[blood_res_1$net == "Blood (GTEx)", ], mapping = aes(x = Centrality, y = Enrichment, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  geom_bar(data = blood_res_2[blood_res_2$net == "Blood (GTEx)", ], mapping = aes(x = Centrality, y = Enrichment, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  scale_fill_brewer(palette = "BrBG") + theme_classic2() + xlab("") + ylab("Enrichment") +
  geom_hline(yintercept=1, colour = "black", linetype = 2, linewidth = 0.4) +
  geom_errorbar(data = blood_res_1[blood_res_1$net == "Blood (GTEx)", ], mapping = aes(x = Centrality, ymin = Enrichment - Enrichment_std_error, ymax = Enrichment + Enrichment_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) +
  geom_errorbar(data = blood_res_2[blood_res_2$net == "Blood (GTEx)", ], mapping = aes(x = Centrality, ymin = Enrichment - Enrichment_std_error, ymax = Enrichment + Enrichment_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) + 
  scale_alpha_manual(values = c("All genes" = 0.3, "All genes + Baseline" = 1)) + 
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom") 


p4 <- ggplot() +
  geom_bar(data = blood_res_1[blood_res_1$net == "Blood (GTEx)", ], mapping = aes(x = Centrality, y = Coefficient, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  geom_bar(data = blood_res_2[blood_res_2$net == "Blood (GTEx)", ], mapping = aes(x = Centrality, y = Coefficient, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  scale_fill_brewer(palette = "BrBG") + theme_classic2() + xlab("") + ylab("Coefficient") +
  geom_hline(yintercept=0, colour = "black", linetype = 2, linewidth = 0.4) +
  geom_errorbar(data = blood_res_1[blood_res_1$net == "Blood (GTEx)", ], mapping = aes(x = Centrality, ymin = Coefficient - Coefficient_std_error, ymax = Coefficient + Coefficient_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) +
  geom_errorbar(data = blood_res_2[blood_res_2$net == "Blood (GTEx)", ], mapping = aes(x = Centrality, ymin = Coefficient - Coefficient_std_error, ymax = Coefficient + Coefficient_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) + 
  scale_alpha_manual(values = c("All genes" = 0.4, "All genes + Baseline" = 1)) + 
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom")

title_blood_GTEx <- ggdraw() + 
  draw_label(
    "Meta-Analysis of 9 Blood Traits (Blood GTEx)",
    fontface = 'bold',
    x = 0,
    size = 16,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

legend_blood_GTEx <- get_legend(p3)
p3 <- p3 + theme(legend.position = "none")
p4 <- p4 + theme(legend.position = "none")
plot_grid(title_blood_GTEx, plot_grid(p3, p4, nrow = 1, rel_widths = c(1, 1)), legend_blood_GTEx, nrow = 3, rel_heights =  c(0.1, 1, 0.1))

```

```{r, fig.width=10, fig.height=4}
blood_res_mean_1 <- blood_res_1 %>% group_by(Centrality, Control, net) %>% summarise_at(vars("Enrichment", "Coefficient", ), mean)
blood_res_sd_1 <- blood_res_1 %>% group_by(Centrality, Control, net) %>% summarise_at(vars("Enrichment", "Coefficient", ), sd)
blood_res_mean_1$Enrichment_sd <- blood_res_sd_1$Enrichment
blood_res_mean_1$Coefficient_sd <- blood_res_sd_1$Coefficient

blood_res_mean_2 <- blood_res_2 %>% group_by(Centrality, Control, net) %>% summarise_at(vars("Enrichment", "Coefficient", ), mean)
blood_res_sd_2 <- blood_res_2 %>% group_by(Centrality, Control, net) %>% summarise_at(vars("Enrichment", "Coefficient", ), sd)
blood_res_mean_2$Enrichment_sd <- blood_res_sd_2$Enrichment
blood_res_mean_2$Coefficient_sd <- blood_res_sd_2$Coefficient

p5a <- ggplot() +
  geom_bar(data = blood_res_mean_1, mapping = aes(x = Centrality, y = Enrichment, fill = net), stat = 'identity', position = 'dodge', colour = "black", alpha = 0.3) +
  scale_fill_brewer(name = "Network", palette = "Set1") + theme_classic2() + xlab("") + ylab("Enrichment") +
  geom_hline(yintercept=1, colour = "black", linetype = 2, linewidth = 0.6) +
  geom_errorbar(data = blood_res_mean_1, mapping = aes(x = Centrality, ymin = Enrichment - Enrichment_sd, ymax = Enrichment + Enrichment_sd, fill = net), width = 0.2, position=position_dodge(0.9)) +
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom")

p5b <- ggplot() +
  geom_bar(data = blood_res_mean_2, mapping = aes(x = Centrality, y = Enrichment, fill = net), stat = 'identity', position = 'dodge', colour = "black", alpha = 1) +
  scale_fill_brewer(name = "Network", palette = "Set1") + theme_classic2() + xlab("") + ylab("Enrichment") +
  geom_hline(yintercept=1, colour = "black", linetype = 2, linewidth = 0.6) +
  geom_errorbar(data = blood_res_mean_2, mapping = aes(x = Centrality, ymin = Enrichment - Enrichment_sd, ymax = Enrichment + Enrichment_sd, fill = net), width = 0.2, position=position_dodge(0.9)) +
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom")

p6a <- ggplot() +
  geom_bar(data = blood_res_mean_1, mapping = aes(x = Centrality, y = Coefficient, fill = net), alpha = 0.3, stat = 'identity', position = 'dodge', colour = "black") +
  scale_fill_brewer(name = "Network", palette = "Set1") + theme_classic2() + xlab("") + ylab("Coefficient") +
  geom_hline(yintercept=0, colour = "black", linetype = 2, linewidth = 0.6) +
  geom_errorbar(data = blood_res_mean_1, mapping = aes(x = Centrality, ymin = Coefficient - Coefficient_sd, ymax = Coefficient + Coefficient_sd, fill = net), width = 0.2, position=position_dodge(0.9)) +
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom")

p6b <- ggplot() +
  geom_bar(data = blood_res_mean_2, mapping = aes(x = Centrality, y = Coefficient, fill = net), alpha = 1, stat = 'identity', position = 'dodge', colour = "black") +
  scale_fill_brewer(name = "Network", palette = "Set1") + theme_classic2() + xlab("") + ylab("Coefficient") +
  geom_hline(yintercept=0, colour = "black", linetype = 2, linewidth = 0.6) +
  geom_errorbar(data = blood_res_mean_2, mapping = aes(x = Centrality, ymin = Coefficient - Coefficient_sd, ymax = Coefficient + Coefficient_sd, fill = net), width = 0.2, position=position_dodge(0.9)) +
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom")


title_blood_a <- ggdraw() + 
  draw_label(
    "Meta-Analysis of 9 Blood Related Traits (Conditioned on All genes)",
    fontface = 'bold',
    x = 0,
    size = 16,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

title_blood_b <- ggdraw() + 
  draw_label(
    "Meta-Analysis of 9 Blood Related Traits (Conditioned on All genes and Baseline)",
    fontface = 'bold',
    x = 0,
    size = 16,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

legend_blood_a <- get_legend(p5a)
p5a <- p5a + theme(legend.position = "none")
p6a <- p6a + theme(legend.position = "none")
plot_grid(title_blood_a, plot_grid(p5a, p6a, nrow = 1, rel_widths = c(1, 1)), legend_blood_a, nrow = 3, rel_heights =  c(0.1, 1, 0.1))

legend_blood_b <- get_legend(p5b)
p5b <- p5b + theme(legend.position = "none")
p6b <- p6b + theme(legend.position = "none")
plot_grid(title_blood_b, plot_grid(p5b, p6b, nrow = 1, rel_widths = c(1, 1)), legend_blood_b, nrow = 3, rel_heights =  c(0.1, 1, 0.1))

```

## CNS traits

```{r, fig.width=10, fig.height=4}
cns_indep_traits <- c("PASS_Alzheimers_Jansen2019","PASS_Epilepsy_Anney_2014","PASS_Parkinsons_23andMe_Corces2020",
                      "PASS_BIP_Stahl2019", "PASS_SmokingCessation_Liu2019","UKB_460K.body_WHRadjBMIz",
                      "PASS_BDSCZ_Ruderfer2018", "PASS_MDD_Wray2018", "PASS_DrinksPerWeek_Liu2019") 
cns_res <- readRDS(paste0(resDir, "cns_res.rds"))
cns_res_1 <- cns_res[cns_res$Control == "All genes", ]
cns_res_2 <- cns_res[cns_res$Control == "All genes + Baseline", ]

cns_res_mean_1 <- cns_res_1 %>% group_by(Centrality, Control, net) %>% summarise_at(vars("Enrichment", "Coefficient", ), mean)
cns_res_sd_1 <- cns_res_1 %>% group_by(Centrality, Control, net) %>% summarise_at(vars("Enrichment", "Coefficient", ), sd)
cns_res_mean_1$Enrichment_sd <- cns_res_sd_1$Enrichment
cns_res_mean_1$Coefficient_sd <- cns_res_sd_1$Coefficient

cns_res_mean_2 <- cns_res_2 %>% group_by(Centrality, Control, net) %>% summarise_at(vars("Enrichment", "Coefficient", ), mean)
cns_res_sd_2 <- cns_res_2 %>% group_by(Centrality, Control, net) %>% summarise_at(vars("Enrichment", "Coefficient", ), sd)
cns_res_mean_2$Enrichment_sd <- cns_res_sd_2$Enrichment
cns_res_mean_2$Coefficient_sd <- cns_res_sd_2$Coefficient


p7 <- ggplot() +
  geom_bar(data = cns_res_1[cns_res_1$net == "CNS (GTEx)", ], mapping = aes(x = Centrality, y = Enrichment, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  geom_bar(data = cns_res_2[cns_res_2$net == "CNS (GTEx)", ], mapping = aes(x = Centrality, y = Enrichment, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  scale_fill_brewer(palette = "BrBG") + theme_classic2() + xlab("") + ylab("Enrichment") +
  geom_hline(yintercept=1, colour = "black", linetype = 2, linewidth = 0.4) +
  geom_errorbar(data = cns_res_1[cns_res_1$net == "CNS (GTEx)", ], mapping = aes(x = Centrality, ymin = Enrichment - Enrichment_std_error, ymax = Enrichment + Enrichment_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) +
  geom_errorbar(data = cns_res_2[cns_res_2$net == "CNS (GTEx)", ], mapping = aes(x = Centrality, ymin = Enrichment - Enrichment_std_error, ymax = Enrichment + Enrichment_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) + 
  scale_alpha_manual(values = c("All genes" = 0.3, "All genes + Baseline" = 1)) + 
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom") 


p8 <- ggplot() +
  geom_bar(data = cns_res_1[cns_res_1$net == "CNS (GTEx)", ], mapping = aes(x = Centrality, y = Coefficient, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  geom_bar(data = cns_res_2[cns_res_2$net == "CNS (GTEx)", ], mapping = aes(x = Centrality, y = Coefficient, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  scale_fill_brewer(palette = "BrBG") + theme_classic2() + xlab("") + ylab("Coefficient") +
  geom_hline(yintercept=0, colour = "black", linetype = 2, linewidth = 0.4) +
  geom_errorbar(data = cns_res_1[cns_res_1$net == "CNS (GTEx)", ], mapping = aes(x = Centrality, ymin = Coefficient - Coefficient_std_error, ymax = Coefficient + Coefficient_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) +
  geom_errorbar(data = cns_res_2[cns_res_2$net == "CNS (GTEx)", ], mapping = aes(x = Centrality, ymin = Coefficient - Coefficient_std_error, ymax = Coefficient + Coefficient_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) + 
  scale_alpha_manual(values = c("All genes" = 0.4, "All genes + Baseline" = 1)) + 
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom")

title_cns_GTEx <- ggdraw() + 
  draw_label(
    paste0("Meta-Analysis of ", length(cns_indep_traits),  " CNS Traits (CNS GTEx)"),
    fontface = 'bold',
    x = 0,
    size = 16,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

legend_CNS_GTEx <- get_legend(p7)
p7 <- p7 + theme(legend.position = "none")
p8 <- p8 + theme(legend.position = "none")
plot_grid(title_cns_GTEx, plot_grid(p7, p8, nrow = 1, rel_widths = c(1, 1)), legend_CNS_GTEx, nrow = 3, rel_heights =  c(0.1, 1, 0.2))

```


```{r, fig.width=10, fig.height=4}
p9 <- ggplot() +
  geom_bar(data = cns_res_1[cns_res_1$net == "CNS consensus", ], mapping = aes(x = Centrality, y = Enrichment, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  geom_bar(data = cns_res_2[cns_res_2$net == "CNS consensus", ], mapping = aes(x = Centrality, y = Enrichment, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  scale_fill_brewer(palette = "BrBG") + theme_classic2() + xlab("") + ylab("Enrichment") +
  geom_hline(yintercept=1, colour = "black", linetype = 2, linewidth = 0.4) +
  geom_errorbar(data = cns_res_1[cns_res_1$net == "CNS consensus", ], mapping = aes(x = Centrality, ymin = Enrichment - Enrichment_std_error, ymax = Enrichment + Enrichment_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) +
  geom_errorbar(data = cns_res_2[cns_res_2$net == "CNS consensus", ], mapping = aes(x = Centrality, ymin = Enrichment - Enrichment_std_error, ymax = Enrichment + Enrichment_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) + 
  scale_alpha_manual(values = c("All genes" = 0.3, "All genes + Baseline" = 1)) + 
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom") 


p10 <- ggplot() +
  geom_bar(data = cns_res_1[cns_res_1$net == "CNS consensus", ], mapping = aes(x = Centrality, y = Coefficient, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  geom_bar(data = cns_res_2[cns_res_2$net == "CNS consensus", ], mapping = aes(x = Centrality, y = Coefficient, fill = Lambda, alpha = Control), stat = 'identity', position = 'dodge', colour = "black") +
  scale_fill_brewer(palette = "BrBG") + theme_classic2() + xlab("") + ylab("Coefficient") +
  geom_hline(yintercept=0, colour = "black", linetype = 2, linewidth = 0.4) +
  geom_errorbar(data = cns_res_1[cns_res_1$net == "CNS consensus", ], mapping = aes(x = Centrality, ymin = Coefficient - Coefficient_std_error, ymax = Coefficient + Coefficient_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) +
  geom_errorbar(data = cns_res_2[cns_res_2$net == "CNS consensus", ], mapping = aes(x = Centrality, ymin = Coefficient - Coefficient_std_error, ymax = Coefficient + Coefficient_std_error, fill = Lambda), width = 0.2, position=position_dodge(0.9)) + 
  scale_alpha_manual(values = c("All genes" = 0.4, "All genes + Baseline" = 1)) + 
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom")

title_cns_consensus <- ggdraw() + 
  draw_label(
    paste0("Meta-Analysis of ", length(cns_indep_traits),  " CNS Traits (CNS consensus)"),
    fontface = 'bold',
    x = 0,
    size = 16,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

legend_CNS_consensus <- get_legend(p9)
p9 <- p9 + theme(legend.position = "none")
p10 <- p10 + theme(legend.position = "none")
plot_grid(title_cns_consensus , plot_grid(p9, p10, nrow = 1, rel_widths = c(1, 1)), legend_CNS_consensus, nrow = 3, rel_heights =  c(0.1, 1, 0.2))

```


```{r, fig.width=10, fig.height=4}
p11a <- ggplot() +
  geom_bar(data = cns_res_mean_1, mapping = aes(x = Centrality, y = Enrichment, fill = net), stat = 'identity', position = 'dodge', colour = "black", alpha = 0.3) +
  scale_fill_brewer(name = "Network", palette = "Set1") + theme_classic2() + xlab("") + ylab("Enrichment") +
  geom_hline(yintercept=1, colour = "black", linetype = 2, linewidth = 0.6) +
  geom_errorbar(data = cns_res_mean_1, mapping = aes(x = Centrality, ymin = Enrichment - Enrichment_sd, ymax = Enrichment + Enrichment_sd, fill = net), width = 0.2, position=position_dodge(0.9)) +
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom")

p11b <- ggplot() +
  geom_bar(data = cns_res_mean_2, mapping = aes(x = Centrality, y = Enrichment, fill = net), stat = 'identity', position = 'dodge', colour = "black", alpha = 1) +
  scale_fill_brewer(name = "Network", palette = "Set1") + theme_classic2() + xlab("") + ylab("Enrichment") +
  geom_hline(yintercept=1, colour = "black", linetype = 2, linewidth = 0.6) +
  geom_errorbar(data = cns_res_mean_2, mapping = aes(x = Centrality, ymin = Enrichment - Enrichment_sd, ymax = Enrichment + Enrichment_sd, fill = net), width = 0.2, position=position_dodge(0.9)) +
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom")

p12a <- ggplot() +
  geom_bar(data = cns_res_mean_1, mapping = aes(x = Centrality, y = Coefficient, fill = net), alpha = 0.3, stat = 'identity', position = 'dodge', colour = "black") +
  scale_fill_brewer(name = "Network", palette = "Set1") + theme_classic2() + xlab("") + ylab("Coefficient") +
  geom_hline(yintercept=0, colour = "black", linetype = 2, linewidth = 0.6) +
  geom_errorbar(data = cns_res_mean_1, mapping = aes(x = Centrality, ymin = Coefficient - Coefficient_sd, ymax = Coefficient + Coefficient_sd, fill = net), width = 0.2, position=position_dodge(0.9)) +
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom")

p12b <- ggplot() +
  geom_bar(data = cns_res_mean_2, mapping = aes(x = Centrality, y = Coefficient, fill = net), alpha = 1, stat = 'identity', position = 'dodge', colour = "black") +
  scale_fill_brewer(name = "Network", palette = "Set1") + theme_classic2() + xlab("") + ylab("Coefficient") +
  geom_hline(yintercept=0, colour = "black", linetype = 2, linewidth = 0.6) +
  geom_errorbar(data = cns_res_mean_2, mapping = aes(x = Centrality, ymin = Coefficient - Coefficient_sd, ymax = Coefficient + Coefficient_sd, fill = net), width = 0.2, position=position_dodge(0.9)) +
  theme(plot.title = element_text(face="bold", size = 16), axis.text = element_text(size = 12, face = "bold"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
        legend.text = element_text(size = 12, face = "bold"), legend.title = element_text(size = 12, face = "bold"), 
        axis.title = element_text(size = 12, face = "bold"), legend.position = "bottom")


title_cns_a <- ggdraw() + 
  draw_label(
    "Meta-Analysis of 9 CNS Related Traits (Conditioned on All genes)",
    fontface = 'bold',
    x = 0,
    size = 16,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

title_cns_b <- ggdraw() + 
  draw_label(
    "Meta-Analysis of 9 CNS Related Traits (Conditioned on All genes and Baseline)",
    fontface = 'bold',
    x = 0,
    size = 16,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

legend_cns_a <- get_legend(p11a)
p11a <- p11a + theme(legend.position = "none")
p12a <- p12a + theme(legend.position = "none")
plot_grid(title_cns_a, plot_grid(p11a, p12a, nrow = 1, rel_widths = c(1, 1)), legend_cns_a, nrow = 3, rel_heights =  c(0.1, 1, 0.1))

legend_cns_b <- get_legend(p11b)
p11b <- p11b + theme(legend.position = "none")
p12b <- p12b + theme(legend.position = "none")
plot_grid(title_cns_b, plot_grid(p11b, p12b, nrow = 1, rel_widths = c(1, 1)), legend_cns_b, nrow = 3, rel_heights =  c(0.1, 1, 0.1))

```

